{
  "formatVersion": "1.1",
  "component": {
    "group": "github.chorman0773.sentry",
    "module": "sentry-text",
    "version": "2.0-SNAPSHOT-2020-11-27T23:01:20.750581866Z",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "ageawzcqizbvlnt5em3nsotvku"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-text-2.0.jar",
          "url": "sentry-text-2.0.jar",
          "size": 24702,
          "sha512": "46fda72ddbe9807527839f5df07468e3a1f5b7b31c6b468728432296a1411e9515f2ef2908a46ff3fae18a043e4b02f99a1e226545f0c950fa83db8f121994e2",
          "sha256": "973e01a6f34e296bab43d650412a02bfddaf681bf16c86c085724d62378b8651",
          "sha1": "bd52664f603bb3858c3c2a7595d377563b582380",
          "md5": "2aac47a6361d897f34f5c8aa7cae50ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "sentry-text-2.0.jar",
          "url": "sentry-text-2.0.jar",
          "size": 24702,
          "sha512": "46fda72ddbe9807527839f5df07468e3a1f5b7b31c6b468728432296a1411e9515f2ef2908a46ff3fae18a043e4b02f99a1e226545f0c950fa83db8f121994e2",
          "sha256": "973e01a6f34e296bab43d650412a02bfddaf681bf16c86c085724d62378b8651",
          "sha1": "bd52664f603bb3858c3c2a7595d377563b582380",
          "md5": "2aac47a6361d897f34f5c8aa7cae50ca"
        }
      ]
    }
  ]
}
